export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCESS = "FETCH_PRODUCTS_SUCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";



export const FETCH_PRODUCT_DETAIL_START = "FETCH_PRODUCT_DETAIL_START";
export const FETCH_PRODUCT_DETAIL_SUCESS = "FETCH_PRODUCT_DETAIL_SUCESS";
export const FETCH_PRODUCT_DETAIL_FAILED = "FETCH_PRODUCT_DETAIL_FAILED";
